import React from 'react'
import { Header } from '../../components/shared/Header'
import { BottomNav } from '../../components/shared/BottomNav'
import { Card } from '../../components/shared/Card'
import { EmptyState } from '../../components/shared/EmptyState'
import { useQuery } from '@tanstack/react-query'
import api from '../../services/api'
import { Download, Eye, FileText, Award, Share2 } from 'lucide-react'

/**
 * Student documents page with certificates, transcripts, and ID
 */
export default function StudentDocuments() {
  const { data: documents = [] } = useQuery({
    queryKey: ['student', 'documents'],
    queryFn: async () => {
      const response = await api.get('/students/documents')
      return response.data
    }
  })

  const mockDocuments = [
    {
      id: 1,
      name: 'Grade Card - Semester 1',
      type: 'transcript',
      date: '2024-02-15',
      size: '1.2 MB'
    },
    {
      id: 2,
      name: 'Attendance Certificate',
      type: 'certificate',
      date: '2024-01-30',
      size: '0.8 MB'
    },
    {
      id: 3,
      name: 'Student ID Card',
      type: 'id',
      date: '2023-06-01',
      size: '0.5 MB'
    }
  ]

  const getDocumentIcon = (type) => {
    const iconMap = {
      transcript: FileText,
      certificate: Award,
      id: Award
    }
    return iconMap[type] || FileText
  }

  return (
    <div className="min-h-screen bg-gray-50 pb-24 lg:pb-0">
      <Header title="Documents" />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* DigiLocker Integration */}
        <Card className="mb-8 bg-gradient-to-r from-primary-50 to-primary-100 border-primary-200">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-semibold text-primary-900 mb-2">Push to DigiLocker</h3>
              <p className="text-sm text-primary-700">Push your official documents to your DigiLocker account for lifetime access</p>
            </div>
            <button className="btn-primary py-2 px-4">Push Documents</button>
          </div>
        </Card>

        {/* Documents List */}
        <div className="space-y-4">
          {mockDocuments.length > 0 ? (
            mockDocuments.map(doc => {
              const Icon = getDocumentIcon(doc.type)
              return (
                <Card key={doc.id} className="flex items-center justify-between p-4">
                  <div className="flex items-center gap-4 flex-1">
                    <div className="p-3 bg-primary-100 rounded-lg">
                      <Icon className="h-6 w-6 text-primary-700" />
                    </div>
                    <div className="flex-1">
                      <p className="font-semibold text-gray-900">{doc.name}</p>
                      <p className="text-sm text-gray-600">{doc.date} • {doc.size}</p>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <button className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg">
                      <Eye className="h-5 w-5" />
                    </button>
                    <button className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg">
                      <Download className="h-5 w-5" />
                    </button>
                    <button className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg">
                      <Share2 className="h-5 w-5" />
                    </button>
                  </div>
                </Card>
              )
            })
          ) : (
            <Card>
              <EmptyState
                icon={FileText}
                title="No Documents Yet"
                description="Your official documents will appear here once they are generated by your school"
              />
            </Card>
          )}
        </div>

        {/* Document Types Info */}
        <Card className="mt-8">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">Available Document Types</h3>
          <div className="grid sm:grid-cols-3 gap-4">
            <div className="p-4 border border-gray-200 rounded-lg">
              <p className="font-semibold text-gray-900 mb-1">Grade Cards</p>
              <p className="text-sm text-gray-600">Semester-wise grade transcripts with details</p>
            </div>
            <div className="p-4 border border-gray-200 rounded-lg">
              <p className="font-semibold text-gray-900 mb-1">Certificates</p>
              <p className="text-sm text-gray-600">Attendance and achievement certificates</p>
            </div>
            <div className="p-4 border border-gray-200 rounded-lg">
              <p className="font-semibold text-gray-900 mb-1">ID Documents</p>
              <p className="text-sm text-gray-600">Student ID and official identification</p>
            </div>
          </div>
        </Card>
      </main>

      <BottomNav />
    </div>
  )
}
